on: workflow_dispatch
name: Initial publish on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_CMD: git submodule update --init --remote && bundle exec jekyll build --config '_config.yml,_config_staging.yml'
        NETLIFY_DIR: _site
